language: node_js

node_js:
  - stable

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - node_modules/karma/bin/karma start --browsers Firefox --single-run

addons:
  firefox: "latest"